### ISSUE TITLE
 NoSuchMethodError: No top-level getter 'callbackDispatcher' declared.

### ISSUE THREAD

**Issue by tony123S** [vrtdev/flutter_workmanager#159]
This is how I setup in my project.

**PageA**

 ```
IconButton(
      icon: Icon(Icons.done),
      onPressed: () {
       _bloc.submit();
 })
```
**bloc**

  ```
static void callbackDispatcher() {
    Workmanager.executeTask((task, inputData) {
      print(
          "Native called background task: "); //simpleTask will be emitted here.
      return Future.value(true);
    });
  }

     Future submit() async {
       final title = _title.value;    
       Workmanager.initialize(callbackDispatcher, isInDebugMode: true);
       Workmanager.registerOneOffTask(title, Consts.UPLOAD_IMAGE);     
      }
```
Everytime I press the iconbutton in pageA, I will get this error:

> call E/flutter ( 6710): [ERROR:flutter/shell/common/shell.cc(199)] Dart Error: Unhandled exception: E/flutter ( 6710): NoSuchMethodError: No top-level getter 'callbackDispatcher' declared. E/flutter ( 6710): Receiver: top-level E/flutter ( 6710): Tried calling: callbackDispatcher E/flutter ( 6710): #0
> NoSuchMethodError._throwNew (dart:core-patch/errors_patch.dart:202:5) E/flutter ( 6710): [ERROR:flutter/runtime/dart_isolate.cc(461)] Could not resolve main entrypoint function. E/flutter ( 6710): [ERROR:flutter/shell/common/engine.cc(212)] Could not run the isolate. E/flutter ( 6710): [ERROR:flutter/shell/common/engine.cc(137)] Engine not prepare and launch isolate. E/flutter ( 6710): [ERROR:flutter/shell/common/shell.cc(437)] Could not launch engine with configuration.

**Comment by petermnt** [comment]
The `initialize` method is a Future. Can you try an `await` on the `initialize` before calling `Workmanager.registerOneOffTask`

**Comment by tony123S** [comment]
I still get the same issue

**Comment by tony123S** [comment]
And I need to add a static if we want to define `callbackDispatcher` in bloc?

**Comment by tony123S** [comment]
But I able to receive a notification .. What is the issue?

**Comment by petermnt** [comment]
The function can not be a member function of the bloc.
Try making the function a top level function instead.

**Comment by tony123S** [comment]
If I want to upload image in background, it not possible?

**bloc**

```
 static void callbackDispatcher() {
    WidgetsFlutterBinding.ensureInitialized();
    Workmanager.executeTask((task, inputData) {
       var response = await _repo.submitImages();   // so it can upload at background
      return Future.value(true);
    });
  }
```

**Comment by petermnt** [comment]
It is possible, but not in this way.
The background task cannot use objects from your main isolate.
If you want to submit the images through  your repo, you will need to make another instance of your repo that can be used in the background.

If you really need to  communicate to your UI you can have a look at the solution in issue #151, but if you don't I suggest you just let your background method make its own dependencies.

**Comment by tony123S** [comment]
> you will need to make another instance of your repo that can be used in the background.

Can you assist me on this?  Or provide me some useful link if you don't mind? 
Thanks.

**Comment by petermnt** [comment]
You have the variable `_repo`, which is probably an instance of some kind of class `FooRepository`.
Instead of using `_repo` you should make `callbackDispatcher` a top level repo that just makes its own instance of `FooRepository`.
If it needs some data you should pass it to the `registerTask` function and retrieve it from `inputData`

**Comment by tony123S** [comment]
Where should I put `callbackDispatcher` for the repo? Outside of main too?

**Comment by petermnt** [comment]
Yes, it should be a top level function, so outside of the main.

**Comment by tony123S** [comment]
Is this what you mean?

```void callbackDispatcher() {
  Workmanager.executeTask((task, inputData)async {

    Repository _repo = Repository();
    switch (task) {
      case Consts.UPLOAD_IMAGE:
         // call submit images in repo
        break;
    }

    return Future.value(true);
  });
}
```

**Comment by tony123S** [comment]
It make sense ! Let me try and update you ^^

**Comment by tony123S** [comment]
But what is the correct way to write this in bloc? `callbackDispatcher` not defined.

**bloc**
 ```
  Future submit() async {
        final title = _title.value;

            Workmanager.initialize(
              callbackDispatcher,    
              isInDebugMode: false,
            );
            Workmanager.registerOneOffTask(title, Consts.UPLOAD_IMAGE);
            Navigator.pop(context);
          } 
```

**Comment by tony123S** [comment]
@petermnt  I follow your idea, but get stuck.

This is my top function class
```

void main() => runApp(MyApp());

void callbackDispatcher() {
  Workmanager.executeTask((task, inputData) async {
    switch (task) {
      case Consts.UPLOAD_IMAGE:
          ....          
        Repository _repo = Repository();
        try {
          var result = await _repo.submit();
        } catch (e) {
        }
        break;
    }   
    return Future.value(true);
  });
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
        providers: globalProviders,
        child: MaterialApp(
          debugShowCheckedModeBanner: false,
          title: 'xxx',
          theme: ThemeData(
            accentIconTheme: const IconThemeData.fallback().copyWith(
              color: Colors.white,
            ),
            primaryTextTheme: TextTheme(title: TextStyle(color: Colors.white)),
            primarySwatch: Colors.orange,
            primaryIconTheme: const IconThemeData.fallback().copyWith(
              color: Colors.white,
            ),
          ),
          localizationsDelegates: [
            const LocalizationDelegate(),
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate
          ],
          supportedLocales: [
            const Locale('en', ''),
            const Locale('zh', ''),
          ],
          onGenerateRoute: Router.generateRoute,
          initialRoute: SplashScreen.ROUTE,
        ));
  }
}
```
**repo**

 ```
 class Repository {
  final Dao _dao;
  final Service _service;

  Repository({@required dao, @required service})
      : _dao = dao,
        _service = service;
       ....

      Future submit() async {

        ABC abc = ABC();

        var request = http.MultipartRequest(
            "POST",
            Uri.parse(
                "https://xxx"));

        request.fields['xxx'] = xxx;
        ));

        try {
          var streamedResponse = await request.send();
          var response = http.Response.fromStream(streamedResponse);
               .....
          await _dao.insert(abc);
          return true;
        } catch (e) {
            ....
        }
      }
```
This is my globalProviders.

```
List<SingleChildCloneableWidget> globalProviders = [
  ...independentServices,
  ...dependentServices,
];

List<SingleChildCloneableWidget> independentServices = [
  Provider.value(value: ABCDb()),
  Provider.value(value: ABCClient()),
];

List<SingleChildCloneableWidget> dependentServices = [
  ProxyProvider<ABCDb, ABCDao>(
      update: (context, githubDb, userDao) => ABCDao(githubDb)),
  ProxyProvider<ABCClient, ABCService>(
      update: (context, githubClient, githubService) =>
          ABCService.create(githubClient.chopperClient),
      dispose: (context, githubService) => githubService.client.dispose()),
  ProxyProvider2<ABCDao, ABCService, ABCRepository>(
      update: (context, userDao, abcService, abcRepository) =>
          ABCRepository(
              abcDao: userDao, abcService: abcService))
];
```
**Error**

> I/flutter (24969): Caught Bad state: Cannot add new events after calling close
> I/flutter (24969): NoSuchMethodError: The method 'insert' was called on null.
> I/flutter (24969): Receiver: null
> I/flutter (24969): Tried calling: insert(Instance of 'ABC')
> I/flutter (24969):  Invalid argument(s)

It seems like I not initialize the dao. How can I initialize it? Would appreciate if you can help.

**Comment by ahmed3ssem** [comment]
i have the same issue , did you find a solution for this ?

**Comment by tony123S** [comment]
> i have the same issue , did you find a solution for this ?

You need to define that method outside of main

**Comment by ahmed3ssem** [comment]
@tony123S  
i declared 'callbackDispatcher' in another class and the initialize of workmanager in main like this 
void main(){
  runApp(MyApp());
  Workmanager.initialize(
      LoginScreen.callbackDispatcher, // The top level function, aka callbackDispatcher
      isInDebugMode: true // If enabled it will post a notification whenever the task is running. Handy for debugging tasks
  );
  Workmanager.registerOneOffTask("1", "simpleTask"); //Android only (see below)
}

but still getting this error 'NoSuchMethodError: No top-level getter 'callbackDispatcher' declared.' ,

**Comment by tony123S** [comment]
You can't declare `callbackDispatcher` in another class. If you need to do so, you need to add `staitc`.

**Comment by dmiedev** [comment]
> You can't declare `callbackDispatcher` in another class.

That's weird considering the fact that in the README it says it may be a static function,

**Comment by dmiedev** [comment]
> > You can't declare `callbackDispatcher` in another class.
> 
> That's weird considering the fact that in the README it says it may be a static function,

Hello, @petermnt 
Could we get a fix in README please? It's confusing now.

**Comment by neoacevedo** [comment]
No matter if callBackDispatcher is declared outside of any class, this will launch the error.

**Comment by moldstadt** [comment]
I am seeing the same behaviour and my callbackDispatcher is a global function. This only started happening after upgrading Flutter from 1.26.0-2.0.pre.167 to 2.1.0-13.0.pre.219.

**Comment by nadavfin** [comment]
Hey, I did what petermnt suggested i.e write the function outside the main method (top-level function)' remove the static modifier and it eliminates the error

**Comment by banderberg** [comment]
I have the same problem, I call initialize and registerPeriodicTask in main() before runApp, await everything, and I still get the error `No top-level getter 'callbackDispatcher' declared.`
